# Generated by Django 4.2.28 on 2026-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_booking_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_collapsing',
            field=models.BooleanField(default=False),
        ),
    ]
